name: moodscope
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    # UI & Animations
  cupertino_icons:
  flutter_animate:
  fl_chart:
  lottie:
  glassmorphism:
  toastification:

  # State Management
  provider:

  # Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:

  # Camera & ML
  camera: ^0.11.2
  camera_android: ^0.10.10+7

  # tflite_v2:
  tflite_flutter: ^0.11.0
  image:

  # Utilities
  shared_preferences:
  intl:
  uuid:

  # Music API
  http:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
