// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz8PTvA8PoNww_xUhHdFBWMVax7dyFFJ0',
    appId: '1:478296170395:web:8719ea2b60900721638b3e',
    messagingSenderId: '478296170395',
    projectId: 'moodscope-app',
    authDomain: 'moodscope-app.firebaseapp.com',
    storageBucket: 'moodscope-app.firebasestorage.app',
    measurementId: 'G-0MWEB98M6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOIc6KKQO46noxF414J-2kmVmCc9JXYvo',
    appId: '1:478296170395:android:c25ccf8d816f3d46638b3e',
    messagingSenderId: '478296170395',
    projectId: 'moodscope-app',
    storageBucket: 'moodscope-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbzeJa-DOmZdPex8fCyF1GwRtGFlfRKH8',
    appId: '1:478296170395:ios:956c97c2d5ba5add638b3e',
    messagingSenderId: '478296170395',
    projectId: 'moodscope-app',
    storageBucket: 'moodscope-app.firebasestorage.app',
    iosBundleId: 'com.example.faceEmotionDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbzeJa-DOmZdPex8fCyF1GwRtGFlfRKH8',
    appId: '1:478296170395:ios:956c97c2d5ba5add638b3e',
    messagingSenderId: '478296170395',
    projectId: 'moodscope-app',
    storageBucket: 'moodscope-app.firebasestorage.app',
    iosBundleId: 'com.example.faceEmotionDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz8PTvA8PoNww_xUhHdFBWMVax7dyFFJ0',
    appId: '1:478296170395:web:4c98853121309c98638b3e',
    messagingSenderId: '478296170395',
    projectId: 'moodscope-app',
    authDomain: 'moodscope-app.firebaseapp.com',
    storageBucket: 'moodscope-app.firebasestorage.app',
    measurementId: 'G-40XH1YTN5Q',
  );
}
